// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCourse6_7.Data;

#nullable disable

namespace WebApiCourse6_7.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20240222143643_CheckSeedMigration4")]
    partial class CheckSeedMigration4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiCourse6_7.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityDescription = "Cillum nulla culpa nisi commodo. Veniam adipisicing ipsum consectetur cupidatat exercitation nisi quis. Ea non labore dolore officia amet do commodo cupidatat. Sunt irure ut quis ea dolor labore incididunt. Elit occaecat commodo mollit ex excepteur nisi. Magna ad ipsum dolore eiusmod ea eiusmod anim in dolor incididunt labore.\r\n",
                            CityName = "Monroe"
                        },
                        new
                        {
                            CityId = 2,
                            CityDescription = "Deserunt tempor incididunt nulla veniam cillum esse in elit. Consectetur quis laboris ut ipsum ea qui officia dolore excepteur enim quis elit cupidatat. Dolore cillum nisi incididunt laboris mollit nulla sit irure esse velit labore sunt tempor voluptate. Qui do velit nulla nulla mollit amet proident minim veniam cupidatat duis non. Incididunt Lorem ullamco ut proident commodo tempor in cillum nulla esse sunt pariatur consequat non. Mollit est commodo magna amet ipsum aute sunt amet qui ullamco dolore aliqua cupidatat.\r\n",
                            CityName = "Anna"
                        },
                        new
                        {
                            CityId = 3,
                            CityDescription = "Est duis proident duis occaecat duis nostrud voluptate quis dolore. Anim ea velit eu elit. Minim aliqua labore est do ut elit tempor ex eu. Exercitation do cupidatat Lorem dolor fugiat commodo fugiat est. Mollit amet tempor eu consequat nisi Lorem incididunt commodo anim eiusmod sunt.\r\n",
                            CityName = "Mae"
                        });
                });

            modelBuilder.Entity("WebApiCourse6_7.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("PointDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PointId");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");
                });

            modelBuilder.Entity("WebApiCourse6_7.Entities.PointOfInterest", b =>
                {
                    b.HasOne("WebApiCourse6_7.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WebApiCourse6_7.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
