// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCourse6_7.Data;

#nullable disable

namespace WebApiCourse6_7.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20240224091222_TestSkillSeedCityMigration")]
    partial class TestSkillSeedCityMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiCourse6_7.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityDescription = "Laboris qui sit irure minim est. Et sit Lorem qui do irure esse aliqua eiusmod ex ullamco ullamco sunt exercitation. Occaecat enim consequat reprehenderit in proident officia irure cillum. Dolor pariatur consequat officia tempor in. Exercitation Lorem in occaecat pariatur amet. Excepteur minim veniam est laboris labore Lorem non cupidatat dolore enim.\r\n",
                            CityName = "Kennedy"
                        },
                        new
                        {
                            CityId = 2,
                            CityDescription = "Deserunt adipisicing ullamco officia Lorem mollit officia eu sit. Voluptate in elit commodo elit sit veniam sunt mollit ea labore duis laborum tempor nulla. Aute Lorem tempor et dolore cupidatat enim elit cupidatat aliqua in dolor cillum. Ad voluptate eiusmod id ut.\r\n",
                            CityName = "Hull"
                        },
                        new
                        {
                            CityId = 3,
                            CityDescription = "Officia aliqua id adipisicing elit sint aliquip consectetur do eiusmod. Occaecat ipsum ex nisi reprehenderit exercitation non proident occaecat aliquip anim ut veniam. Cupidatat irure eiusmod ex nostrud consectetur aliquip nostrud magna sint ullamco anim Lorem. Eiusmod consectetur culpa nostrud reprehenderit et commodo occaecat aute exercitation aute do. Duis sunt irure quis labore consectetur nulla consequat incididunt velit. Mollit ex commodo incididunt qui.\r\n",
                            CityName = "Gilliam"
                        },
                        new
                        {
                            CityId = 4,
                            CityDescription = "Eu consequat occaecat Lorem incididunt sit fugiat ex duis cupidatat. Ea deserunt cupidatat nostrud pariatur fugiat. Velit exercitation veniam aliquip nulla quis ex ipsum quis voluptate mollit duis incididunt. Aliquip nostrud cupidatat Lorem sit amet ea. Ipsum id consectetur ex consectetur. Consectetur ipsum id eiusmod officia esse ea. Ut tempor enim veniam ipsum irure sunt.\r\n",
                            CityName = "Corrine"
                        },
                        new
                        {
                            CityId = 5,
                            CityDescription = "Culpa duis eiusmod do eu amet in ea laborum aliqua. Ad eiusmod magna minim dolor ullamco quis nulla do mollit eu magna. Mollit nulla magna culpa voluptate cupidatat proident incididunt aute Lorem nisi eu laborum. Aliqua do mollit esse duis ad sunt ipsum adipisicing nulla tempor sit.\r\n",
                            CityName = "Hughes"
                        },
                        new
                        {
                            CityId = 6,
                            CityDescription = "Quis labore ipsum sunt est. Ex sunt culpa tempor duis duis irure excepteur. Occaecat officia deserunt in aliqua. Aliquip consequat labore elit nulla velit cillum anim commodo ea et incididunt ex est velit. Ad sunt ea velit culpa minim.\r\n",
                            CityName = "Lindsey"
                        },
                        new
                        {
                            CityId = 7,
                            CityDescription = "Eu culpa est consequat ut irure eu incididunt ad reprehenderit ullamco cillum cillum. Amet sint deserunt do in mollit. Cupidatat do anim elit sit et elit.\r\n",
                            CityName = "Christi"
                        },
                        new
                        {
                            CityId = 8,
                            CityDescription = "Laborum aliquip laborum qui commodo commodo eiusmod mollit reprehenderit ipsum ex dolor culpa. Officia nostrud dolor eiusmod ut amet. Sit ut elit nulla ex pariatur nulla do et aliqua deserunt quis irure excepteur et. Officia consectetur tempor mollit ullamco.\r\n",
                            CityName = "Dale"
                        },
                        new
                        {
                            CityId = 9,
                            CityDescription = "Aute cillum eu aliquip consequat nostrud officia sunt proident cillum eiusmod voluptate dolore exercitation ut. Dolore sunt sunt dolore nulla aute. Qui amet laborum est deserunt aliquip duis duis sunt. Do laborum fugiat ad laborum tempor. Incididunt in ex labore esse irure. Aliquip sunt proident commodo irure. Labore cupidatat est et sint aute laborum ex ea ullamco minim et incididunt laborum.\r\n",
                            CityName = "Krystal"
                        },
                        new
                        {
                            CityId = 10,
                            CityDescription = "Fugiat est ad magna ipsum. Officia veniam minim mollit ipsum voluptate ipsum ea aliquip labore adipisicing duis aute non. Excepteur consectetur quis fugiat incididunt cupidatat culpa ut est commodo non qui sit amet. Adipisicing commodo velit Lorem laboris adipisicing. Consequat ea fugiat enim nulla eiusmod non laboris duis aliquip ea. Cupidatat adipisicing esse aute Lorem est nisi ipsum ut ad consectetur incididunt sunt sint. Enim tempor culpa incididunt consequat Lorem cupidatat irure est ipsum.\r\n",
                            CityName = "Sawyer"
                        });
                });

            modelBuilder.Entity("WebApiCourse6_7.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("PointDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PointId");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            PointId = 1,
                            CityId = 1,
                            PointDescription = "Ex qui aliquip aliqua velit eiusmod. Lorem consequat proident cupidatat duis consequat. Tempor eiusmod magna minim aliqua Lorem magna incididunt voluptate in consectetur enim ex. Cillum duis qui occaecat consectetur non proident consequat proident laborum ex incididunt quis. Irure exercitation sunt minim tempor laborum.\r\n",
                            PointName = "Fleming"
                        },
                        new
                        {
                            PointId = 2,
                            CityId = 1,
                            PointDescription = "Veniam velit eiusmod sit aute non. Ullamco officia in consectetur Lorem tempor ipsum ullamco laboris voluptate minim proident. Cupidatat id dolore deserunt magna cupidatat non incididunt. Eu commodo cillum laborum laborum in duis incididunt duis laboris. Deserunt enim reprehenderit exercitation occaecat aute cillum voluptate nisi ad ex sint irure do. Reprehenderit labore eu id proident ad occaecat aute sunt.\r\n",
                            PointName = "Ortiz"
                        },
                        new
                        {
                            PointId = 3,
                            CityId = 10,
                            PointDescription = "Anim laboris minim elit consectetur. Proident duis ut dolor amet sunt veniam pariatur laborum esse exercitation adipisicing sunt adipisicing. Exercitation veniam tempor labore veniam consequat anim laboris labore qui mollit do cillum duis.\r\n",
                            PointName = "Ashlee"
                        },
                        new
                        {
                            PointId = 4,
                            CityId = 10,
                            PointDescription = "Ad cillum occaecat consectetur id do. Irure deserunt aute anim magna proident duis reprehenderit enim aliqua aliquip do labore. Esse commodo elit deserunt laborum sit.\r\n",
                            PointName = "Carey"
                        },
                        new
                        {
                            PointId = 5,
                            CityId = 10,
                            PointDescription = "Elit amet labore aute aliqua pariatur proident fugiat dolore non ut pariatur ut. Esse Lorem veniam dolor dolor ea. Enim et sunt nisi ut culpa aute ea et pariatur irure labore ad. Occaecat labore ea in adipisicing cupidatat. Adipisicing Lorem consectetur eu laborum sit cupidatat ullamco eiusmod.\r\n",
                            PointName = "Hattie"
                        });
                });

            modelBuilder.Entity("WebApiCourse6_7.Entities.PointOfInterest", b =>
                {
                    b.HasOne("WebApiCourse6_7.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WebApiCourse6_7.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
